### ISSUE TITLE
add links between citation of words in glossary and their definition

### ISSUE THREAD

**Issue by slashformotion** [RolfBremer/gloss-awe#1]
It would be great to be able to have links to the definition of a word when citing said words

**Comment by RolfBremer** [comment]
The best I achieved in this direction is to have the show rule for the marker to create a hyperlink to a Label at the Glossary page. 

```typ
// glossary-marker display : this rule makes the glossary marker visible
// and adds a hyperlink to the Glossar.
#show figure.where(kind: "jkrb_glossary"): it => [#link(<Glossar>)[#it.body]]
```

I will integrate that in the sample code shortly.
Unfortunately I was not successful with dynamically created labels. I can create them, but the typst compiler complains that the labels do not exist, when referencing them.

**Comment by slashformotion** [comment]
I think that is an acceptable tradeoff
